### ISSUE TITLE
Philips 32pfl2807/12

### ISSUE THREAD

**Issue by armadillo76** [irplus-remote/irplus-codes.github.io#200]
32pfl2807/12 code missing from ir yours list code for ir product.thanks

**Comment by irplus-remote** [comment]
Hi, please test other Philips PFL Codes and Philips TV Generic. should work. I'm closing this issue, I can't list every philips model separately since the codes are always the same.

If you have tested _all_ of them and nothing works / you are missing a button or something like that i need more detailed info about your device (Phone, Android version, did other devices work? )
