### ISSUE TITLE
Sony STR-D495 and RM-U306A [missing repeat]

### ISSUE THREAD

**Issue by KarlBaumann** [irplus-remote/irplus-codes.github.io#239]
Hi! Thanks for the awesome app!
Is it possible to somehow record ir signals from my existing remote to see why app does not work?

**Comment by irplus-remote** [comment]
Hi, it is possible with HTC / LG. What phone are you using?

**Comment by KarlBaumann** [comment]
Wow, that was quick!

I have galaxy s5. And I managed to get STR-D495 working by changing repeat from 1 to 2.

**Comment by irplus-remote** [comment]
Thanks for the info, will update the codefile like you said!

**Comment by KarlBaumann** [comment]
Anyway,  are you saying that it is possible to record existing signal only with htc and lg? 
I have here some Chinese LEDs I would like to record.

**Comment by irplus-remote** [comment]
Yes recording is not possible with Samsung (They only have a transmitter not a receiver) - The S7 even removed the transmitter (no more IR on that one)

Alternative way of course would be to use a PC / Raspberry etc. running LIRC

See here for a full guide:
https://irplus-remote.github.io#codes

**Comment by KarlBaumann** [comment]
Ok, I will get LIRC for RPI.
Yeah, S5 is the last good phone with removable battery, sd card and other nice features.

Btw, just theoretically, wouldnt it be possible to read IR with phone camera?

**Comment by irplus-remote** [comment]
Unfortunately not. We can do some math :)
The carrier frequency is about 38000hz (38000 on off per second, cam can record at roughly 60fps~). Even if we just guess the carrier frequency since its mostly 38-40khz, a bit duration is on average 600µs. So to recognize reliably each bit sent, the cam would need to take a picture each 600µs. So yo see its VERY far from 60fps. With a cam you just see it flash once and thats it. 

Even the IR-proximity sensor which most phones have is too slow for that job.

Could you create a new issue please with the photo / brand of chinese LED you have? Cause i already got codes for some of those
