### ISSUE TITLE
LG Learned Codes - converting

### ISSUE THREAD

**Issue by Telemachus1977** [irplus-remote/irplus-codes.github.io#305]
My Note 4 cannot learn IR codes.  So my buddy used his LG V20 to learn the buttons for my bidet (Intelliseat Bidet Remote).  When I import these into the Note 4 it says invalid IR code or not submitted by emitter.

The learned codes look nothing like most IR Hex codes.  I'm not sure if they even work since we did this away from the house with just the remote.

One of the button codes looks like this:

1:[3, 0, 0, 0, 93, 9, -98, -78, 0, 2, 79, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 53, -1, -1, 0, 0, 0, 55, 0, 0, 0, -85, -77, 28, 40, 82, -128, -108, 48, 124, -121, -80, 48, 3, 0, 43, 4, 9, 36, -107, -33, -42, 112, 0, 73, 0, -110, 73, 73, -110, 81, 41, -92, -110, 41, 20, -118, 37, 36, -110, 73, 18, 73, 69, -94, 81, 73, -110, 73, 37, -94, -118, 80, 16, -128]

**Comment by irplus-remote** [comment]
Hi, unfortunately it is not possible to move LG learned codes to other devices - they only work on the device it was learned with. This is because LG decided to encrypt the codes for some reason i don't know. If you want the plain codes you need to use LIRC or HTC

https://irplus-remote.github.io/#codes

**Comment by Telemachus1977** [comment]
That makes sense, thank you so much for your prompt response

**Comment by molafir** [comment]
please add remote control MKJ39170828 lg codes
