### ISSUE TITLE
Learn Code ans Smart TV

### ISSUE THREAD

**Issue by yacinegithub** [irplus-remote/irplus-codes.github.io#357]
Nice app in general, but i have some questions.
1- why i can't find the "learn code" button?

2- is that button programed to hide itself if for other smartphones except HTC ans LG, or hide itself when it doesn't detect IR Receiver?

3- is there a possibility to run the app  on a Smart TV and make smart TV learning code throught his IR blaster Receiver like the Broadlink RM mini 3 ans RM Pro?
And good luck for you.

**Comment by irplus-remote** [comment]
Hi,  learning is possible only with LG and HTC, only they have the hardware for it. Well actually no - some Huawei or chinese phones can do it too, but they  have no public API for it, so i can't implement it - if you know how let me know

3.) not possible unfortunately due to hardware limitation 

For what device do you need codes?

**Comment by yacinegithub** [comment]
Thank you My devices is Changhong smart tvs

**Comment by yacinegithub** [comment]
But why it is impossible when smart TV has infrared Receiver and it's running under Android Os.
And look At the Broadlink topology it is the dame.
Thank u again.

**Comment by irplus-remote** [comment]
The full model number of the tv? (to check for codes)

It is impossible because learning is provided by hardware and os dependent apis. so even with thr hardware it does not work on all platforms due to android limitations.

For htc there is a special api to learn:
https://www.htcdev.com/devcenter/opensense-sdk/partner-apis/htc-ir-api/?cid=htcblog_calling-ir-apps

However if you have a raspberry or other linux machine you can use irrecord/lirc to gather codes

**Comment by yacinegithub** [comment]
Actually My device it's name "Condor LEDU8200" it's a Algerian local brand "condor" but i found after search that it's actually the Chaineese company Changhong constructed that Smart tv for Condor.

**Comment by yacinegithub** [comment]
And let me suggest interesting thing for you:
is to add a voice commands to tour app, sio user van command his device juste with his voice.
By using "Saiy app API" 
Link: https://github.com/brandall76/API-Example-App.
And thank you again bro.

**Comment by irplus-remote** [comment]
Did you test the available chang hong codes?

I will not add a dependency to a third party api with GPL3 licence and trademark.

But in can see if i can add voice command via the Google API ;)

**Comment by yacinegithub** [comment]
And by the way i steal have a doubt about possibility to learn code ir for smart TVs, i will install your app un My smart TV And check if the Learn code Button will be shown or not.
And for the voice commands it's a serious issue because all developped apps like yours are going through voice commands (you know kind of Artificial inteliegance).
Accept My user experience feedback and suggestions as user and as developer too.
Thank you very much And good luck.

**Comment by yacinegithub** [comment]
And by the way Google API is a good choice and gone be a great work.

**Comment by irplus-remote** [comment]
Learn button will be shown only on LG and HTC. As said the learning api is only available on those as Android stock only has sendIR implemented, so it is simply impossible as of now to learn IR codes on a stock android without a manufacturer api.

Only theoretic way would be a rooted device with lirc and a driver for lirc to use it. Some KODI tv boxes can learn too because they have a driver for the included remote.

Still - easiest way to learn codes is a raspberry

**Comment by yacinegithub** [comment]
Let me tell you that finally i found an app specially for my smartphone "Condor p8 lite" called "Condor smart remote" and it has a learning code functionality and it's work in a good way.
And i Decompiled that app with an android app called "Show Java" and i found that they use the same "Htc CirControle" Library in that app. 
!!!

**Comment by irplus-remote** [comment]
Ok this is indeed interesting, i could try to build an apk which enables the learn button for condor and uses the HTC api, then you can try

**Comment by yacinegithub** [comment]
Ok waiting..

**Comment by irplus-remote** [comment]
Can you please send me an email via the app? 

(Information -> Contact)

This email will contain info i need to enable the button, since it is based on a whitelist

**Comment by yacinegithub** [comment]
msndeyacine@hotmail.com

**Comment by irplus-remote** [comment]
As said, i need it via the app (Info -> Contact )

**Comment by yacinegithub** [comment]
I sended you Email Via the app from that Email address.

**Comment by irplus-remote** [comment]
Nothing here, then copy + paste the line of the email template of the app and post it here.

Example : 

irplus 1.9.3 (build 269)
Android device: SAMSUNG|SM-N9005|LRX21V.N9005XXSGBPL6|5.0|de

**Comment by yacinegithub** [comment]
This the Email content if you didn't get the Email msg

irplus 1.9.3 (build 269)
Android device: CONDOR|PGN610|PGN610|6.0|en

Message:
*** This message has been sent using Condor Plume P8 Lite ***

**Comment by irplus-remote** [comment]
Ok here is the APK - try and let me know if it works

https://drive.google.com/file/d/1i8wmfXwUaogyfK3Wv4YIRtml6Xl1CP6V/view?usp=sharing

**Comment by yacinegithub** [comment]
Ok wait some time..

**Comment by yacinegithub** [comment]
Unfortunutly No.

**Comment by irplus-remote** [comment]
But the button appears? Errors?

**Comment by yacinegithub** [comment]
And the ir blaster doesn't transmit light in thag apk release.
I checked that using camera

**Comment by yacinegithub** [comment]
The button appears
But sty flashing in red color
Without catching errors

**Comment by irplus-remote** [comment]
ok then probably its not possible to use the HTC code as-is and it needs modification. Probably it is easier to try to setup a second application only for learning, but since i dont have that hardware itsbasically impossible for me. Feel free to try

Here is the latest apk, without the modification, then you can install it and at least sending ir works again
https://drive.google.com/file/d/1hgNxhzmOvk6I4GiRM2TcdZ8OsL6dOdOO/view?usp=sharing

**Comment by yacinegithub** [comment]
Ok
